const express=require("express"),{spawn}=require("child_process"),fs=require("fs/promises"),path=require("path"),os=require("os");
const app=express(); app.use(express.json()); const PORT=Number(process.env.PORT||3000), SAMPLE="https://www.youtube.com/watch?v=gf-urtMZObY", jobs=new Map();
function run(cmd,args){return new Promise(resolve=>{const p=spawn(cmd,args,{env:process.env});let stdout="",stderr="";p.stdout?.on("data",d=>stdout+=d);p.stderr?.on("data",d=>stderr+=d);p.on("error",e=>resolve({code:-1,stdout,stderr:stderr+"\n"+e.message}));p.on("close",code=>resolve({code,stdout,stderr}));});}
async function test(id,url){const j=jobs.get(id),dir=await fs.mkdtemp(path.join(os.tmpdir(),"seblunky-"));try{
j.status="checking";j.steps.push("Checking Python, yt-dlp and FFmpeg...");
const py=await run("python3",["--version"]),yd=await run("yt-dlp",["--version"]),ff=await run("ffmpeg",["-version"]);
if(py.code||yd.code||ff.code)throw Error(`Dependency check failed\n${py.stderr}\n${yd.stderr}\n${ff.stderr}`);
j.steps.push(`${py.stdout.trim()} | yt-dlp ${yd.stdout.trim()} | FFmpeg ready`);
j.status="metadata";const m=await run("yt-dlp",["--no-playlist","--print","%(title)s|%(duration)s|%(id)s",url]);if(m.code)throw Error("Metadata failed:\n"+m.stderr);j.steps.push("Metadata: "+m.stdout.trim());
j.status="downloading";j.steps.push("Downloading 15-second media test locally...");
const d=await run("yt-dlp",["--no-playlist","--force-ipv4","--js-runtimes","node","--download-sections","*0-15","--force-keyframes-at-cuts","-f","bv*[height<=360]+ba/b[height<=360]/b","--merge-output-format","mp4","-o",path.join(dir,"test.%(ext)s"),url]);
if(d.code)throw Error("Media download failed:\n"+d.stderr);
const names=await fs.readdir(dir);let bytes=0;for(const n of names)bytes+=(await fs.stat(path.join(dir,n))).size;j.status="success";j.steps.push(`SUCCESS: ${names.join(", ")} (${(bytes/1048576).toFixed(1)} MB)`);}
catch(e){j.status="failed";j.error=String(e.message||e)}finally{j.finishedAt=new Date().toISOString();await fs.rm(dir,{recursive:true,force:true}).catch(()=>{})}}
app.get("/health",(_,r)=>r.json({ok:true}));
app.get("/",(_,r)=>r.type("html").send(`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>Seblunky Clip Farm</title><style>body{font-family:-apple-system,system-ui;background:#0b0b0f;color:#fff;padding:24px}main{max-width:680px;margin:auto}.c{background:#17171f;border:1px solid #333;border-radius:18px;padding:22px}input,button{box-sizing:border-box;width:100%;padding:15px;margin:8px 0;border-radius:11px;font-size:16px}input{background:#0f0f15;color:#fff;border:1px solid #444}button{font-weight:700;border:0}pre{white-space:pre-wrap;word-break:break-word}</style><main><div class=c><h1>Seblunky Clip Farm</h1><p>Railway YouTube acquisition gate.</p><input id=u value="${SAMPLE}"><button onclick=s()>Run Railway Test</button><pre id=o>Ready.</pre></div></main><script>async function s(){o.textContent="Starting...";let r=await fetch("/test",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({url:u.value})}),j=await r.json();if(!j.id){o.textContent=JSON.stringify(j,null,2);return}let t=setInterval(async()=>{let x=await(await fetch("/status/"+j.id)).json();o.textContent=JSON.stringify(x,null,2);if(["success","failed"].includes(x.status))clearInterval(t)},1500)}</script>`));
app.post("/test",(q,r)=>{const url=String(q.body?.url||SAMPLE);if(!/^https:\/\/(www\.)?(youtube\.com|youtu\.be)\//i.test(url))return r.status(400).json({error:"Use a YouTube URL."});const id=Date.now().toString(36)+Math.random().toString(36).slice(2,8);jobs.set(id,{id,status:"queued",steps:[],startedAt:new Date().toISOString()});setImmediate(()=>test(id,url));r.status(202).json({id})});
app.get("/status/:id",(q,r)=>{const j=jobs.get(q.params.id);j?r.json(j):r.status(404).json({error:"Job not found"})});
app.listen(PORT,"0.0.0.0",()=>console.log(`Seblunky Clip Farm listening on ${PORT}`));
